version: 2
updates:
  - package-ecosystem: 'uv'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '10:00'
      timezone: 'Asia/Tokyo'
    groups:
      dependencies:
        patterns:
          - '*'
